In [2]:
#PROBS 6, 7, 8
import numpy as np

6.		For problem 6: Create	a	5x5	random	array.	Then,	normalize	the	array—meaning,	multiply	the	
original	array	by	a	factor	that	makes	the	entire	new	array	sum	to	1.

In [5]:
x=np.random.random((3,3))
x

array([[0.12744384, 0.50032578, 0.34123267],
       [0.75639496, 0.53684156, 0.30738313],
       [0.86822696, 0.59491058, 0.41272845]])

In [6]:
np.sum(x)

4.445487926902954

In [8]:
NormalizedArray=x/np.sum(x)
NormalizedArray

array([[0.02866813, 0.11254688, 0.07675933],
       [0.17014892, 0.120761  , 0.06914497],
       [0.19530521, 0.13382346, 0.0928421 ]])

In [9]:
np.sum(NormalizedArray)

1.0000000000000002

For Prob 7. From	a	random	array	Y	=	np.random.uniform(0,10,10),	create	a	new	array	Z	that	
just	has	the	integer	part	of	all	the	numbers	that	were	in	Y.	That	is,	chop	off	
everything	after	the	decimal.

In [10]:
#Check out np.trunc, np.floor, np.round
Y=np.random.uniform(0,10,10)
Y


array([5.79723229, 8.08476299, 9.62189095, 4.97746155, 4.62358668,
       6.30493842, 3.25921268, 4.28356746, 3.63411289, 8.72733043])

In [11]:
np.floor(Y)

array([5., 8., 9., 4., 4., 6., 3., 4., 3., 8.])

8. For Prob 8 Make	a	function	that	converts	a	given	pair	of	Cartesian	coordinates	(x,y)	to	polar	
coordinates	(r,	theta),	where	theta	is	in	degrees.

In [12]:
#x = r cos theta
#y = r sin theta
# theta = np.arctan(y/x)  #But check that it's in degrees
def Cart2Pol(MyX,MyY):
    MyR=np.sqrt(MyX**2+MyY**2)
    MyTheta = 3
    return MyR,MyTheta

r,theta=Cart2Pol(2,2)

In [13]:
r,theta

(2.8284271247461903, 3)

In [14]:
r**2

8.000000000000002