In [3]:
import numpy as np
s=5
s

5

Documentation here https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html

In [5]:
s=np.zeros(12)
s

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
s.reshape(3,4) ##3 rows, 4 cols This does NOT modify s. It will print its output if it's the last thing in the cell
#To change s, you should assign s the new value with an equals = sign
s

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
s=s.reshape(4,3) #4 rows, 3 cols
s

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
s.fill(5) ##This DOES modify s! But it won't print its output even if it's the last line in the cell, you have to
#type the variable name


In [11]:
s 
#And if you do s=s.fill(5) you are going to get NOTHING because s.fill(5) doesn't return anything
#.Fill modifies the array "in place." 
#So, which methods return a new array, and which ones modify the existing array? 
##Is there a rule that would help? Like, "Filling changes value while reshaping changes structure"
#Not really. For example .resize is a structure-changing method that WILL modify the array in place.


array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [12]:
s.resize(2,6) #Resize does the same thing as reshape, but is different because it modifies s.
#To sum it up, you have to read the documentation or test it out.
#One telltale sign was that the .fill method didn't print its output, while the .reshape one DID print
#because it returned a value


In [13]:

s 

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])