In [898]:
#read in a coordinate file in mm and some align marks
#turn it into an exp formatted file 
#porting expalignjump from matlab to python
#ckh june 2016
import numpy as np


#later I want to have the user input the measured coords on a web form, for now I want a text input box
#but how to be interactive? http://stackoverflow.com/questions/35361038/using-ipython-ipywidget-to-create-a-variable
from ipywidgets import widgets,interact #besides text, interact has a slider and more. PythonAnywhere has ipywidgets

In [899]:
#Had to go to a terminal and enter    jupyter nbextension enable --py --sys-prefix widgetsnbextension
#tried it again and THEN had to stop and restart this notebook to get the widgets working
input_text=widgets.Text()
input_text  #x1,y1,x2,y2 measured coords of align marks in millimeters

In [900]:
#measmarkstring=input_text.value #grab what the user typed for the measured coords
measmarkstring='-25,0,25,0'

In [901]:
#now to break that string into pieces
measmarks=[float(measmark) for measmark in measmarkstring.split(',')]

In [902]:
[measxleft,measyleft,measxright,measyright]=measmarks
[drawnxleft,drawnyleft,drawnxright,drawnyright]=[-30.0,0.0,30.0,0.0]#default alignmark position

Calculate shift and rotation angle:

In [903]:
measxcenter=np.mean([measxleft,measxright])
measycenter=np.mean([measyleft,measyright])
drawnxcenter=np.mean([drawnxleft,drawnxright])
drawnycenter=np.mean([drawnyleft,drawnyright])
#measxcenter,measycenter,drawnxcenter,drawnycenter
tanangle=(measyright-measyleft)/(measxright-measxleft) #assumes drawn marks are along same horizontal line
offangle=np.arctan(tanangle) #it's in radians and assumes you're not off by 90 deg or more
shift=[measxcenter-drawnxcenter,measycenter-drawnycenter]
offangle,shift

(0.0, [0.0, 0.0])

In [904]:
#define the coordinate conversions matlab has that numpy doesnt
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(phi,rho)

def pol2cart(phi, rho):
    x = rho * np.cos(phi)
    y = rho * np.sin(phi)
    return(x, y)

In [905]:
#now get the text file containing coordinates, it will expect a csv text file
stitchdata= np.loadtxt('HuichanRemodel.csv', delimiter=',')


In [906]:
stitchdata

array([[ 14.695,   3.023],
       [ 13.821,   5.839],
       [ 12.438,   8.387],
       [ 10.607,  10.606],
       [  8.387,  12.438],
       [  5.839,  13.821],
       [  3.023,  14.695],
       [  0.   ,  15.   ],
       [ -3.023,  14.695],
       [ -5.839,  13.821],
       [ -8.387,  12.438],
       [-10.607,  10.606],
       [-12.438,   8.387],
       [-13.821,   5.839],
       [-14.695,   3.023],
       [-15.   ,   0.   ],
       [-14.734,  -2.984],
       [-13.935,  -5.693],
       [-13.335,  -6.93 ],
       [-11.735,  -9.138],
       [-10.032, -10.671],
       [ -8.028, -11.999],
       [ -6.495, -12.789],
       [ -5.287, -14.008],
       [ -5.   , -15.346],
       [ -5.   , -17.877],
       [ -5.   , -20.227],
       [ -5.   , -22.693],
       [ -5.   , -25.107],
       [ -5.   , -27.517],
       [ -5.   , -30.   ],
       [ -2.646, -30.   ],
       [  0.   , -30.   ],
       [  2.528, -30.   ],
       [  5.   , -30.   ],
       [  5.   , -27.576],
       [  5.   , -24.93 ],
 

In [907]:
x=stitchdata[:,0]
y=stitchdata[:,1]

In [908]:
y

array([  3.023,   5.839,   8.387,  10.606,  12.438,  13.821,  14.695,
        15.   ,  14.695,  13.821,  12.438,  10.606,   8.387,   5.839,
         3.023,   0.   ,  -2.984,  -5.693,  -6.93 ,  -9.138, -10.671,
       -11.999, -12.789, -14.008, -15.346, -17.877, -20.227, -22.693,
       -25.107, -27.517, -30.   , -30.   , -30.   , -30.   , -30.   ,
       -27.576, -24.93 , -22.049, -19.166, -16.228, -12.7  , -10.   ,
       -10.   ,  -8.992,  -7.205,  -5.854,  -5.102,  -4.974,  -4.397,
        -3.181,  -1.487,   0.   ,   1.946,   3.536,   4.607,   5.   ,
         4.607,   3.536,   1.946,   1.008,   0.   ,   0.   ,  -1.946,
        -3.535,  -4.607,  -5.   ,  -4.607,  -3.535,  -1.946,   0.   ,
         3.023])

In [909]:
[theta,r]=cart2pol(x,y)

In [910]:
[x,y]=pol2cart(theta+offangle,r)

In [911]:
x=x+shift[0]
y=y+shift[1]

In [912]:
x


array([  1.46950000e+01,   1.38210000e+01,   1.24380000e+01,
         1.06070000e+01,   8.38700000e+00,   5.83900000e+00,
         3.02300000e+00,   9.18485099e-16,  -3.02300000e+00,
        -5.83900000e+00,  -8.38700000e+00,  -1.06070000e+01,
        -1.24380000e+01,  -1.38210000e+01,  -1.46950000e+01,
        -1.50000000e+01,  -1.47340000e+01,  -1.39350000e+01,
        -1.33350000e+01,  -1.17350000e+01,  -1.00320000e+01,
        -8.02800000e+00,  -6.49500000e+00,  -5.28700000e+00,
        -5.00000000e+00,  -5.00000000e+00,  -5.00000000e+00,
        -5.00000000e+00,  -5.00000000e+00,  -5.00000000e+00,
        -5.00000000e+00,  -2.64600000e+00,   1.83697020e-15,
         2.52800000e+00,   5.00000000e+00,   5.00000000e+00,
         5.00000000e+00,   5.00000000e+00,   5.00000000e+00,
         5.00000000e+00,   5.00000000e+00,   5.00000000e+00,
         5.00000000e+00,   4.89800000e+00,   4.14600000e+00,
         2.79600000e+00,   1.00800000e+00,  -5.11000000e-01,
        -2.38300000e+00,

In [913]:
dx=np.diff(x)
dy=np.diff(y)

In [914]:
#find the extent of the matrix
dxmax=np.max(np.absolute(dx))
dymax=np.max(np.absolute(dy))
diffmax=np.max([dxmax,dymax])
#maximum allowed is 127
x

array([  1.46950000e+01,   1.38210000e+01,   1.24380000e+01,
         1.06070000e+01,   8.38700000e+00,   5.83900000e+00,
         3.02300000e+00,   9.18485099e-16,  -3.02300000e+00,
        -5.83900000e+00,  -8.38700000e+00,  -1.06070000e+01,
        -1.24380000e+01,  -1.38210000e+01,  -1.46950000e+01,
        -1.50000000e+01,  -1.47340000e+01,  -1.39350000e+01,
        -1.33350000e+01,  -1.17350000e+01,  -1.00320000e+01,
        -8.02800000e+00,  -6.49500000e+00,  -5.28700000e+00,
        -5.00000000e+00,  -5.00000000e+00,  -5.00000000e+00,
        -5.00000000e+00,  -5.00000000e+00,  -5.00000000e+00,
        -5.00000000e+00,  -2.64600000e+00,   1.83697020e-15,
         2.52800000e+00,   5.00000000e+00,   5.00000000e+00,
         5.00000000e+00,   5.00000000e+00,   5.00000000e+00,
         5.00000000e+00,   5.00000000e+00,   5.00000000e+00,
         5.00000000e+00,   4.89800000e+00,   4.14600000e+00,
         2.79600000e+00,   1.00800000e+00,  -5.11000000e-01,
        -2.38300000e+00,

In [915]:
x=np.round(x*10)
y=np.round(y*10)

In [916]:
xjumploc=np.where(np.absolute(np.diff(x))>12) #where is like matlab find,   #i put 12, was 63
#except numpy.where can be used w/2 args for more versatility. with one arg
#my result will be in xjumplocs[0]
xjumploc=xjumploc[0]
xjumploc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 18, 19, 20, 21, 30,
       31, 32, 33, 44, 45, 46, 47, 48, 53, 54, 55, 56, 63, 64, 65, 66])

In [917]:
#now shift each jump location cumulatively ahead of time
xjumploc=xjumploc+range(0,len(xjumploc))
xjumploc

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 30, 32, 34, 36, 46,
       48, 50, 52, 64, 66, 68, 70, 72, 78, 80, 82, 84, 92, 94, 96, 98])

In [918]:
j=1j #this is blowing my mind

In [920]:
xjumploc[0:2]

array([1, 3])

In [921]:
for i in range(0,len(xjumploc)): #insert the x-jumps and renumber everything after them
    print(i)
    jump=np.sign(x[xjumploc[i]+1]-x[xjumploc[i]])*63
    x=np.concatenate((x[0:(xjumploc[i])]+0j,[x[xjumploc[i]]]+jump+1j,x[(xjumploc[i]):len(x)]+0j),axis=0)
    print ('x')
    print(x)  
    #this is super awkward
    #to translate from MATLAB which assumes evertything is complex. 
    #probably should use numpy.insert instead of using the imaginary part as a flag.

    #print([y[xjumploc[i]]]+jump+0j-jump)#Why do I only get to concatenate the complex numbers
    #by adding and subtracting jump...seriously not happy about this
    y=np.concatenate((y[0:(xjumploc[i])]+0j,[y[xjumploc[i]]]+jump+0j-jump,y[(xjumploc[i]):len(y)]+0j),axis=0)

    print ('and y')
    print(y)

0
x
[ 147.+0.j   75.+1.j  138.+0.j  124.+0.j  106.+0.j   84.+0.j   58.+0.j
   30.+0.j    0.+0.j  -30.+0.j  -58.+0.j  -84.+0.j -106.+0.j -124.+0.j
 -138.+0.j -147.+0.j -150.+0.j -147.+0.j -139.+0.j -133.+0.j -117.+0.j
 -100.+0.j  -80.+0.j  -65.+0.j  -53.+0.j  -50.+0.j  -50.+0.j  -50.+0.j
  -50.+0.j  -50.+0.j  -50.+0.j  -50.+0.j  -26.+0.j    0.+0.j   25.+0.j
   50.+0.j   50.+0.j   50.+0.j   50.+0.j   50.+0.j   50.+0.j   50.+0.j
   50.+0.j   50.+0.j   49.+0.j   41.+0.j   28.+0.j   10.+0.j   -5.+0.j
  -24.+0.j  -39.+0.j  -48.+0.j  -50.+0.j  -46.+0.j  -35.+0.j  -19.+0.j
    0.+0.j   19.+0.j   35.+0.j   46.+0.j   49.+0.j   50.+0.j   50.+0.j
   54.+0.j   65.+0.j   81.+0.j  100.+0.j  119.+0.j  135.+0.j  146.+0.j
  150.+0.j  147.+0.j]
[ 58.+0.j]
and y
[  30.+0.j   58.+0.j   58.+0.j   84.+0.j  106.+0.j  124.+0.j  138.+0.j
  147.+0.j  150.+0.j  147.+0.j  138.+0.j  124.+0.j  106.+0.j   84.+0.j
   58.+0.j   30.+0.j    0.+0.j  -30.+0.j  -57.+0.j  -69.+0.j  -91.+0.j
 -107.+0.j -120.+0.j -128.+0.j -14

In [870]:
yjumploc=np.where(np.absolute(np.diff(y))>63)
yjumploc=yjumploc[0]
yjumploc=yjumploc+range(0,len(yjumploc))

In [391]:
for i in range(0,len(yjumploc)): #insert the y-jumps and renumber everything after them
    jump=np.sign(y[yjumploc[i]+1]-y[yjumploc[i]])*63
    x=[x[0:(yjumploc[i]+1)],x[yjumploc[i]],x[(yjumploc[i]+1):len(x)]]
    y=[y[0:(yjumploc[i]+1)],y[yjumploc[i]]+jump+j,y[(yjumploc[i]+1):len(y)]]


In [79]:
#now get the final jump locations
xjumplocs=np.where((np.imag(x))>0)
xjumplocs=xjumplocs[0]
yjumplocs=np.where((np.imag(y))>0)
yjumplocs=yjumplocs[0]
x=np.real(x)#back to normal after finding all the jump locations
y=np.real(y)

In [80]:
y

array([  30.,   58.,   84.,  106.,  124.,  138.,  147.,  150.,  147.,
        138.,  124.,  106.,   84.,   58.,   30.,    0.,  -30.,  -57.,
        -69.,  -91., -107., -120., -128., -140., -153., -179., -202.,
       -227., -251., -275., -300., -300., -300., -300., -300., -276.,
       -249., -220., -192., -162., -127., -100., -100.,  -90.,  -72.,
        -59.,  -51.,  -50.,  -44.,  -32.,  -15.,    0.,   19.,   35.,
         46.,   50.,   46.,   35.,   19.,   10.,    0.,    0.,  -19.,
        -35.,  -46.,  -50.,  -46.,  -35.,  -19.,    0.,   30.])

In [81]:
x

array([ 147.,  138.,  124.,  106.,   84.,   58.,   30.,    0.,  -30.,
        -58.,  -84., -106., -124., -138., -147., -150., -147., -139.,
       -133., -117., -100.,  -80.,  -65.,  -53.,  -50.,  -50.,  -50.,
        -50.,  -50.,  -50.,  -50.,  -26.,    0.,   25.,   50.,   50.,
         50.,   50.,   50.,   50.,   50.,   50.,   50.,   49.,   41.,
         28.,   10.,   -5.,  -24.,  -39.,  -48.,  -50.,  -46.,  -35.,
        -19.,    0.,   19.,   35.,   46.,   49.,   50.,   50.,   54.,
         65.,   81.,  100.,  119.,  135.,  146.,  150.,  147.])

In [82]:
#this will take care of anything <25.4 mm