In [143]:
#read in a coordinate file in mm and some align marks
#turn it into an exp formatted file 
#porting expalignjump from matlab to python
#ckh june 2016
import numpy as np


#later I want to have the user input the measured coords on a web form, for now I want a text input box
#but how to be interactive? http://stackoverflow.com/questions/35361038/using-ipython-ipywidget-to-create-a-variable
from ipywidgets import widgets,interact #besides text, interact has a slider and more. PythonAnywhere has ipywidgets

In [144]:
#Had to go to a terminal and enter    jupyter nbextension enable --py --sys-prefix widgetsnbextension
#tried it again and THEN had to stop and restart this notebook to get the widgets working
input_text=widgets.Text()
input_text  #x1,y1,x2,y2 measured coords of align marks in millimeters

In [145]:
#measmarkstring=input_text.value #grab what the user typed for the measured coords
measmarkstring='-25,0,25,0'

In [146]:
#now to break that string into pieces
measmarks=[float(measmark) for measmark in measmarkstring.split(',')]

In [147]:
[measxleft,measyleft,measxright,measyright]=measmarks
[drawnxleft,drawnyleft,drawnxright,drawnyright]=[-30.0,0.0,30.0,0.0]#default alignmark position

Calculate shift and rotation angle:

In [148]:
measxcenter=np.mean([measxleft,measxright])
measycenter=np.mean([measyleft,measyright])
drawnxcenter=np.mean([drawnxleft,drawnxright])
drawnycenter=np.mean([drawnyleft,drawnyright])
#measxcenter,measycenter,drawnxcenter,drawnycenter
tanangle=(measyright-measyleft)/(measxright-measxleft) #assumes drawn marks are along same horizontal line
offangle=np.arctan(tanangle) #it's in radians and assumes you're not off by 90 deg or more
shift=[measxcenter-drawnxcenter,measycenter-drawnycenter]
offangle,shift

(0.0, [0.0, 0.0])

In [149]:
#define the coordinate conversions matlab has that numpy doesnt
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(phi,rho)

def pol2cart(phi, rho):
    x = rho * np.cos(phi)
    y = rho * np.sin(phi)
    return(x, y)

In [150]:
#now get the text file containing coordinates, it will expect a comma delimited text file
stitchdata= np.loadtxt('HuichanRemodel.csv', delimiter=',')


In [151]:
stitchdata

array([[ 14.695,   3.023],
       [ 13.821,   5.839],
       [ 12.438,   8.387],
       [ 10.607,  10.606],
       [  8.387,  12.438],
       [  5.839,  13.821],
       [  3.023,  14.695],
       [  0.   ,  15.   ],
       [ -3.023,  14.695],
       [ -5.839,  13.821],
       [ -8.387,  12.438],
       [-10.607,  10.606],
       [-12.438,   8.387],
       [-13.821,   5.839],
       [-14.695,   3.023],
       [-15.   ,   0.   ],
       [-14.734,  -2.984],
       [-13.935,  -5.693],
       [-13.335,  -6.93 ],
       [-11.735,  -9.138],
       [-10.032, -10.671],
       [ -8.028, -11.999],
       [ -6.495, -12.789],
       [ -5.287, -14.008],
       [ -5.   , -15.346],
       [ -5.   , -17.877],
       [ -5.   , -20.227],
       [ -5.   , -22.693],
       [ -5.   , -25.107],
       [ -5.   , -27.517],
       [ -5.   , -30.   ],
       [ -2.646, -30.   ],
       [  0.   , -30.   ],
       [  2.528, -30.   ],
       [  5.   , -30.   ],
       [  5.   , -27.576],
       [  5.   , -24.93 ],
 

In [152]:
x=stitchdata[:,0]
y=stitchdata[:,1]

In [153]:
y

array([  3.023,   5.839,   8.387,  10.606,  12.438,  13.821,  14.695,
        15.   ,  14.695,  13.821,  12.438,  10.606,   8.387,   5.839,
         3.023,   0.   ,  -2.984,  -5.693,  -6.93 ,  -9.138, -10.671,
       -11.999, -12.789, -14.008, -15.346, -17.877, -20.227, -22.693,
       -25.107, -27.517, -30.   , -30.   , -30.   , -30.   , -30.   ,
       -27.576, -24.93 , -22.049, -19.166, -16.228, -12.7  , -10.   ,
       -10.   ,  -8.992,  -7.205,  -5.854,  -5.102,  -4.974,  -4.397,
        -3.181,  -1.487,   0.   ,   1.946,   3.536,   4.607,   5.   ,
         4.607,   3.536,   1.946,   1.008,   0.   ,   0.   ,  -1.946,
        -3.535,  -4.607,  -5.   ,  -4.607,  -3.535,  -1.946,   0.   ,
         3.023])

In [154]:
[theta,r]=cart2pol(x,y)

In [155]:
[x,y]=pol2cart(theta+offangle,r)

In [156]:
x=x+shift[0]
y=y+shift[1]

In [157]:
x


array([  1.46950000e+01,   1.38210000e+01,   1.24380000e+01,
         1.06070000e+01,   8.38700000e+00,   5.83900000e+00,
         3.02300000e+00,   9.18485099e-16,  -3.02300000e+00,
        -5.83900000e+00,  -8.38700000e+00,  -1.06070000e+01,
        -1.24380000e+01,  -1.38210000e+01,  -1.46950000e+01,
        -1.50000000e+01,  -1.47340000e+01,  -1.39350000e+01,
        -1.33350000e+01,  -1.17350000e+01,  -1.00320000e+01,
        -8.02800000e+00,  -6.49500000e+00,  -5.28700000e+00,
        -5.00000000e+00,  -5.00000000e+00,  -5.00000000e+00,
        -5.00000000e+00,  -5.00000000e+00,  -5.00000000e+00,
        -5.00000000e+00,  -2.64600000e+00,   1.83697020e-15,
         2.52800000e+00,   5.00000000e+00,   5.00000000e+00,
         5.00000000e+00,   5.00000000e+00,   5.00000000e+00,
         5.00000000e+00,   5.00000000e+00,   5.00000000e+00,
         5.00000000e+00,   4.89800000e+00,   4.14600000e+00,
         2.79600000e+00,   1.00800000e+00,  -5.11000000e-01,
        -2.38300000e+00,

In [158]:
dx=np.diff(x)
dy=np.diff(y)

In [159]:
#find the extent of the matrix
dxmax=np.max(np.absolute(dx))
dymax=np.max(np.absolute(dy))
diffmax=np.max([dxmax,dymax])
#maximum allowed is 127
x

array([  1.46950000e+01,   1.38210000e+01,   1.24380000e+01,
         1.06070000e+01,   8.38700000e+00,   5.83900000e+00,
         3.02300000e+00,   9.18485099e-16,  -3.02300000e+00,
        -5.83900000e+00,  -8.38700000e+00,  -1.06070000e+01,
        -1.24380000e+01,  -1.38210000e+01,  -1.46950000e+01,
        -1.50000000e+01,  -1.47340000e+01,  -1.39350000e+01,
        -1.33350000e+01,  -1.17350000e+01,  -1.00320000e+01,
        -8.02800000e+00,  -6.49500000e+00,  -5.28700000e+00,
        -5.00000000e+00,  -5.00000000e+00,  -5.00000000e+00,
        -5.00000000e+00,  -5.00000000e+00,  -5.00000000e+00,
        -5.00000000e+00,  -2.64600000e+00,   1.83697020e-15,
         2.52800000e+00,   5.00000000e+00,   5.00000000e+00,
         5.00000000e+00,   5.00000000e+00,   5.00000000e+00,
         5.00000000e+00,   5.00000000e+00,   5.00000000e+00,
         5.00000000e+00,   4.89800000e+00,   4.14600000e+00,
         2.79600000e+00,   1.00800000e+00,  -5.11000000e-01,
        -2.38300000e+00,

In [160]:
x=np.round(x*10)
y=np.round(y*10)

In [161]:
xjumploc=np.where(np.absolute(np.diff(x))>63) #where is like matlab find,   #i put 12, was 63
#except numpy.where can be used w/2 args for more versatility. with one arg
#my result will be in xjumplocs[0]
xjumploc=xjumploc[0]
xjumploc

array([], dtype=int64)

In [162]:
#now shift each jump location cumulatively ahead of time
xjumploc=xjumploc+range(0,len(xjumploc))
xjumploc

array([], dtype=float64)

In [163]:
j=1j #this is blowing my mind

In [164]:
for i in range(0,len(xjumploc)): #insert the x-jumps and renumber everything after them
    print(i)
    jump=np.sign(x[xjumploc[i]+1]-x[xjumploc[i]])*63
    x=np.concatenate((x[0:(xjumploc[i])]+0j,[x[xjumploc[i]]]+jump+1j,x[(xjumploc[i]):len(x)]+0j),axis=0)
    print ('x')
    print(x)  
    #this is super awkward
    #to translate from MATLAB which assumes evertything is complex. 
    #probably should use numpy.insert instead of using the imaginary part as a flag.

    #print([y[xjumploc[i]]]+jump+0j-jump)#Why do I only get to concatenate the complex numbers
    #by adding and subtracting jump...seriously not happy about this
    y=np.concatenate((y[0:(xjumploc[i])]+0j,[y[xjumploc[i]]]+jump+0j-jump,y[(xjumploc[i]):len(y)]+0j),axis=0)

    print ('and y')
    print(y)

In [165]:
yjumploc=np.where(np.absolute(np.diff(y))>63)
yjumploc=yjumploc[0]
yjumploc=yjumploc+range(0,len(yjumploc))

In [166]:
for i in range(0,len(yjumploc)): #insert the y-jumps and renumber everything after them
    print(i)
    jump=np.sign(y[yjumploc[i]+1]-y[yjumploc[i]])*63
    x=np.concatenate((x[0:(yjumploc[i])]+0j,[x[yjumploc[i]]]+jump+0j-jump,x[(yjumploc[i]):len(y)]+0j),axis=0)
    print ('x')
    print(x)  
    y=np.concatenate((y[0:(yjumploc[i])]+0j,[y[yjumploc[i]]]+jump+j,y[(yjumploc[i]):len(y)]+0j),axis=0)
    print ('and y')
    print(y)


In [167]:
#now get the final jump locations
xjumplocs=np.where((np.imag(x))>0)
xjumplocs=xjumplocs[0]
yjumplocs=np.where((np.imag(y))>0)
yjumplocs=yjumplocs[0]
x=np.real(x)#back to normal after finding all the jump locations
y=np.real(y)

In [168]:
y

array([  30.,   58.,   84.,  106.,  124.,  138.,  147.,  150.,  147.,
        138.,  124.,  106.,   84.,   58.,   30.,    0.,  -30.,  -57.,
        -69.,  -91., -107., -120., -128., -140., -153., -179., -202.,
       -227., -251., -275., -300., -300., -300., -300., -300., -276.,
       -249., -220., -192., -162., -127., -100., -100.,  -90.,  -72.,
        -59.,  -51.,  -50.,  -44.,  -32.,  -15.,    0.,   19.,   35.,
         46.,   50.,   46.,   35.,   19.,   10.,    0.,    0.,  -19.,
        -35.,  -46.,  -50.,  -46.,  -35.,  -19.,    0.,   30.])

In [169]:
x

array([ 147.,  138.,  124.,  106.,   84.,   58.,   30.,    0.,  -30.,
        -58.,  -84., -106., -124., -138., -147., -150., -147., -139.,
       -133., -117., -100.,  -80.,  -65.,  -53.,  -50.,  -50.,  -50.,
        -50.,  -50.,  -50.,  -50.,  -26.,    0.,   25.,   50.,   50.,
         50.,   50.,   50.,   50.,   50.,   50.,   50.,   49.,   41.,
         28.,   10.,   -5.,  -24.,  -39.,  -48.,  -50.,  -46.,  -35.,
        -19.,    0.,   19.,   35.,   46.,   49.,   50.,   50.,   54.,
         65.,   81.,  100.,  119.,  135.,  146.,  150.,  147.])

In [170]:
#this will take care of anything <25.4 mm
#now would be a good place to plot the xy points, copy matplotlib commands from my other file

In [171]:
if(np.max(np.abs(np.concatenate((np.diff(x),np.diff(y))))))>191:
    print('ERROR: your file has a jump greater than 25.4 mm')
    #return or bail out somehow

In [172]:
#calc the differences dx and dy after scaling and roundoff
dx=np.diff(x)
dy=np.diff(y)

In [173]:
#shift any negative values to positive
shiftxloc=np.where(dx<0) #where is like matlab find,  but can I do with lists somehow
#except numpy.where can be used w/2 args for more versatility. with one arg
#my result will be in xjumplocs[0]
shiftxloc=shiftxloc[0]
dx[shiftxloc]=dx[shiftxloc]+256


In [174]:
dx

array([ 247.,  242.,  238.,  234.,  230.,  228.,  226.,  226.,  228.,
        230.,  234.,  238.,  242.,  247.,  253.,    3.,    8.,    6.,
         16.,   17.,   20.,   15.,   12.,    3.,    0.,    0.,    0.,
          0.,    0.,    0.,   24.,   26.,   25.,   25.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,  255.,  248.,  243.,
        238.,  241.,  237.,  241.,  247.,  254.,    4.,   11.,   16.,
         19.,   19.,   16.,   11.,    3.,    1.,    0.,    4.,   11.,
         16.,   19.,   19.,   16.,   11.,    4.,  253.])

In [175]:
shiftyloc=np.where(dy<0)
shiftyloc=shiftyloc[0]
dy[shiftyloc]=dy[shiftyloc]+256
#oops python has logical indexing like MATLAB this can save time http://stackoverflow.com/questions/12424824/how-i-can-i-conditionally-change-the-values-in-a-numpy-array-taking-into-account
dy


array([  28.,   26.,   22.,   18.,   14.,    9.,    3.,  253.,  247.,
        242.,  238.,  234.,  230.,  228.,  226.,  226.,  229.,  244.,
        234.,  240.,  243.,  248.,  244.,  243.,  230.,  233.,  231.,
        232.,  232.,  231.,    0.,    0.,    0.,    0.,   24.,   27.,
         29.,   28.,   30.,   35.,   27.,    0.,   10.,   18.,   13.,
          8.,    1.,    6.,   12.,   17.,   15.,   19.,   16.,   11.,
          4.,  252.,  245.,  240.,  247.,  246.,    0.,  237.,  240.,
        245.,  252.,    4.,   11.,   16.,   19.,   30.])

In [176]:
#cast the values into uint8 format which will round them off
dx=np.uint8(dx)
dy=np.uint8(dy)
dx

array([247, 242, 238, 234, 230, 228, 226, 226, 228, 230, 234, 238, 242,
       247, 253,   3,   8,   6,  16,  17,  20,  15,  12,   3,   0,   0,
         0,   0,   0,   0,  24,  26,  25,  25,   0,   0,   0,   0,   0,
         0,   0,   0, 255, 248, 243, 238, 241, 237, 241, 247, 254,   4,
        11,  16,  19,  19,  16,  11,   3,   1,   0,   4,  11,  16,  19,
        19,  16,  11,   4, 253], dtype=uint8)

In [177]:
#shift any dx or dy who is exactly 128, down to 127 or the machine will think this is a jump or color change
#I dont think this can happen after the jumps and bail out but here goes
dx[dx==128]=127
dy[dy==128]=127

In [ ]:
#Iterate through dx and dy and insert jumps, designated by 128.
origdx=dx
origdy=dy
dx=[]
dy=[]
for i in range(0,len(origdx)):

